### ISSUE TITLE
Speakers list never finishes loading

### ISSUE THREAD

**Issue by StachuDotNet** [fsharp/zzarchive-community.fsharp.org#85]
@mathias-brandewinder mentioned this in fsharp/fsfoundation#711.

"In the speakers list page, the page never finishes loading and displaying the speakers."

**Comment by StachuDotNet** [comment]
This is due to not having an API key for the Google Maps call.
A few months back, the <script> started requiring a ?key attribute, not currently supplied by the website.

It's generally ok to generate a key and use it in a public site (not a secret), as the end user can just look at the <script> tag anyway. I'll do this shortly in the next commit.

--- 

Edit:
The contents of this subdomain don't seem to actually come directly from the source in this repo. Can anyone give intel as to how the content of this page works? Is there any reason this is in a separate repo?

**Comment by ReedCopsey** [comment]
I fixed this yesterday. Problem was actually invalid json in the jsonp source.
